"""
Reference list of major law firms worldwide.
Used as fallback for extraction when regex patterns don't catch everything.
"""

# Major U.S. and international law firms (276 firms total, deduplicated and alphabetically sorted)
MAJOR_LAW_FIRMS = [
    "A&O Shearman",
    "Akerman LLP",
    "Akin Gump Strauss Hauer & Feld LLP",
    "Allen & Gledhill LLP",
    "Allen & Overy LLP",
    "Alston & Bird LLP",
    "Alto Litigation",
    "Andrews Kurth Kenyon LLP",
    "Andrews Myers, P.C.",
    "Arendt & Medernach",
    "ArentFox Schiff",
    "Arnold & Porter",
    "Asbury Gardner",
    "Ashurst LLP",
    "ASKramer Law LLC",
    "Assouline & Berlowe, P.A.",
    "Axinn Veltrop & Harkrider",
    "Baker Botts LLP",
    "Baker McKenzie LLP",
    "BakerHostetler",
    "Balch & Bingham LLP",
    "Ballard Spahr LLP",
    "Bartkowski PLLC",
    "Bartlit Beck LLP",
    "Beck Redden",
    "Beck Reed Riden LLP",
    "Bell Nunnally & Martin LLP",
    "Bercow Radell Fernandez Larkin & Tapanes",
    "Berger Montague",
    "Bergeson LLP",
    "Berkowitz, Trager & Trager LLC",
    "Berman Tabacco",
    "Beveridge & Diamond, P.C.",
    "Bienert Katzman Littrell Williams LLP",
    "Bird & Bird (America) LLP",
    "Blake, Cassels & Graydon LLP",
    "Blank Rome LLP",
    "Bleichmar Fonti & Auld LLP",
    "Boies Schiller Flexner LLP",
    "Bondurant, Mixson & Elmore LLP",
    "Botkin Chiarello Calaf PLLC",
    "Bowman and Brooke LLP",
    "BoyarMiller",
    "Boyle & Jasari LLP",
    "Bracewell LLP",
    "Bradley Arant Boult Cummings LLP",
    "Brown Rudnick LLP",
    "Bryan Cave Leighton Paisner LLP",
    "Buchalter",
    "Butler Snow LLP",
    "Cadwalader, Wickersham & Taft LLP",
    "Cahill Gordon & Reindel LLP",
    "Cairncross & Hempelmann",
    "Caplin & Drysdale, Chartered",
    "Carter Ledyard & Milburn LLP",
    "Cassidy Levy Kent (USA) LLP",
    "Chaffetz Lindsey LLP",
    "Chamberlain Hrdlicka",
    "Choate, Hall & Stewart",
    "Clark Hill Plc",
    "Cleary Gottlieb Steen & Hamilton LLP",
    "Clifford Chance LLP",
    "Cohen & Gresser LLP",
    "Cohen Ziffer Frenchman & McKenna",
    "Cooley LLP",
    "Covington & Burling LLP",
    "Cowan, Liebowitz & Latman, PC",
    "Cravath, Swaine & Moore LLP",
    "Crawford, Wishnew & Lang PLLC",
    "Crowell & Moring LLP",
    "Curtis, Mallet-Prevost, Colt & Mosle LLP",
    "Davies Ward Phillips & Vineberg LLP",
    "Davis Polk & Wardwell LLP",
    "Davis Wright Tremaine LLP",
    "Davis+Gilbert LLP",
    "De Brauw Blackstone Westbroek",
    "Debevoise & Plimpton LLP",
    "Dechert LLP",
    "Dentons LLP",
    "Diaz Reus International Law Firm",
    "Dickinson Wright PLLC",
    "DLA Piper LLP",
    "Doll Amir & Eley LLP",
    "Elsberg Baker & Maruri PLLC",
    "Faegre Drinker Biddle & Reath",
    "Fenwick & West LLP",
    "Finnegan, Henderson, Farabow, Garrett & Dunner LLP",
    "Foley & Lardner LLP",
    "Frankfurt Kurnit Klein & Selz PC",
    "Freshfields Bruckhaus Deringer LLP",
    "Fried, Frank, Harris, Shriver & Jacobson LLP",
    "Friedman Kaplan Seiler Adelman & Robbins LLP",
    "Fross Zelnick Lehrman & Zissu, P.C.",
    "Gaillard Banifatemi Shelbaya Disputes",
    "Gibbs & Bruns LLP",
    "Gibson, Dunn & Crutcher LLP",
    "Goldman Ismail Tomaselli Brennan & Baum LLP",
    "Goodwin Procter LLP",
    "Greenberg Glusker LLP",
    "Greenberg Traurig LLP",
    "Groom Law Group, Chartered",
    "Gunderson Dettmer LLP",
    "Hallett & Perrin",
    "Hausfeld LLP",
    "Haynes and Boone, L.L.P.",
    "Hecker Fink LLP",
    "Herbert Smith Freehills",
    "Herrick, Feinstein LLP",
    "Hogan Lovells LLP",
    "Hogan Thompson Schuelke LLP",
    "Hoguet Newman Regal & Kenney, LLP",
    "Holland & Knight",
    "Holwell Shuster & Goldberg LLP",
    "Hueston Hennigan LLP",
    "Hughes Hubbard & Reed LLP",
    "Hunton Andrews Kurth LLP",
    "Husch Blackwell LLP",
    "Irell & Manella LLP",
    "Jackson Lewis P.C.",
    "Johnston Clem Gifford PLLC",
    "Jones Day",
    "Jones Walker LLP",
    "K&L Gates LLP",
    "Kaiser PLLC",
    "Kane, Russell, Coleman & Logan, P.C.",
    "Kasowitz LLP",
    "Katsky Korins LLP",
    "Katten Muchin Rosenman LLP",
    "Keller and Heckman LLP",
    "Kelley Drye & Warren LLP",
    "Kessler Topaz Meltzer & Check, LLP",
    "Kim & Chang",
    "King & Spalding LLP",
    "Kirkland & Ellis LLP",
    "KN Legal",
    "Knobbe Martens Olson & Bear LLP",
    "Kramer Levin Naftalis & Frankel LLP",
    "Krevolin Horst, LLC",
    "Kuiper Law Firm PLLC",
    "Labaton Keller Sucharow LLP",
    "Latham & Watkins LLP",
    "Levenfeld Pearlstein",
    "Levine Lee LLP",
    "Lightfoot Franklin & White LLC",
    "Linklaters LLP",
    "Loeb & Loeb LLP",
    "Loyens & Loeff N.V.",
    "Macfarlanes LLP",
    "Manatt, Phelps & Phillips, LLP",
    "Marshall Dennehey, PC",
    "Massumi + Consoli LLP",
    "Mayer Brown LLP",
    "McDermott Will & Emery LLP",
    "McDermott Will & Schulte",
    "Meister Seelig & Fein PLLC",
    "Messerli Kramer",
    "Michelman & Robinson, LLP",
    "Milbank LLP",
    "Miller & Chevalier Chartered",
    "Miller Barondess LLP",
    "Mintz, Levin, Cohn, Ferris, Glovsky and Popeo, P.C.",
    "MoloLamken LLP",
    "Moore & Van Allen, PLLC",
    "Morgan, Lewis & Bockius LLP",
    "Mori Hamada US LLP",
    "Morris, Nichols, Arsht & Tunnell LLP",
    "Morrison & Foerster LLP",
    "Morvillo Abramowitz Grand Iason & Anello P.C.",
    "Moses Singer",
    "Much Shelist, P.C.",
    "Nagashima Ohno & Tsunematsu NY LLP",
    "NautaDutilh N.V.",
    "Neal, Gerber & Eisenberg LLP",
    "Nelson Mullins Riley & Scarborough LLP",
    "Next Legal PLLC.",
    "Nixon Peabody LLP",
    "Norton Rose Fulbright LLP",
    "Nossaman LLP",
    "Nutter, McClennen & Fish, LLP",
    "O'Melveny & Myers LLP",
    "Offit Kurman",
    "Oliva Gibbs PLLC",
    "Olshan Frome Wolosky LLP",
    "Orrick, Herrington & Sutcliffe LLP",
    "Osborne Clarke",
    "Osler, Hoskin & Harcourt LLP",
    "PAG Law",
    "Patterson Belknap Webb & Tyler LLP",
    "Paul Hastings LLP",
    "Paul, Weiss, Rifkind, Wharton & Garrison LLP",
    "Peckar & Abramson, P.C.",
    "Perkins Coie LLP",
    "Perry Law",
    "Phillips Lytle LLP",
    "Pillsbury Winthrop Shaw Pittman LLP",
    "Platt Richmond",
    "Pomerantz LLP",
    "Porter Hedges LLP",
    "Proskauer Rose LLP",
    "Pryor Cashman LLP",
    "Pérez-Llorca",
    "Quinn Emanuel Urquhart & Sullivan LLP",
    "Rajah & Tann LLP",
    "Rathmell Short LLP",
    "Redgrave LLP",
    "Reed Smith LLP",
    "Reid, Collins & Tsai",
    "Reynolds Frizzell LLP",
    "Richards, Layton & Finger, P.A.",
    "Rivkin Radler",
    "Robinson & Cole LLP",
    "Rock Creek Energy Group LLP",
    "Ropes & Gray LLP",
    "Sanchez Fischer Levine, LLP",
    "Sbaiti & Company",
    "Schulte Roth & Zabel LLP",
    "Selendy Gay PLLC",
    "Seward & Kissel LLP",
    "Seyfarth Shaw LLP",
    "Shartsis Friese LLP",
    "Shearman & Sterling LLP",
    "Sheppard, Mullin, Richter & Hampton LLP",
    "Shook, Hardy & Bacon LLP",
    "Shutts & Bowen LLP",
    "Sidley Austin LLP",
    "Simmons & Simmons LLP",
    "Simpson Thacher & Bartlett LLP",
    "Skadden, Arps, Slate, Meagher & Flom LLP",
    "Slaughter and May",
    "Smith Currie Oles",
    "Steptoe LLP",
    "Sterlington PLLC",
    "Sterne, Kessler, Goldstein & Fox PLLC",
    "Stroock & Stroock & Lavan LLP",
    "Sullivan & Cromwell LLP",
    "Sullivan & Worcester LLP",
    "Telecommunications Law Professionals",
    "Tenenbaum Law Group PLLC",
    "The Lanier Law Firm",
    "The Rosen Law Firm",
    "Thompson Hine LLP",
    "Torys LLP",
    "Transaction Advisors Group",
    "Travers Smith LLP",
    "Troutman Pepper Hamilton Sanders LLP",
    "Troutman Pepper Locke LLP",
    "Van Ness Feldman LLP",
    "Vedder Price",
    "Venable LLP",
    "Vinson & Elkins LLP",
    "Wachtell, Lipton, Rosen & Katz",
    "Watson Farley & Williams (New York) LLP",
    "Weil, Gotshal & Manges LLP",
    "White & Case LLP",
    "Wiggin and Dana LLP",
    "Wilkinson Stekloff",
    "Williams & Connolly LLP",
    "Willkie Farr & Gallagher LLP",
    "WilmerHale LLP",
    "Wilson Sonsini Goodrich & Rosati P.C.",
    "Winston & Strawn LLP",
    "Withers",
    "Wolf Greenfield & Sacks",
    "Womble Bond Dickinson LLP",
    "Yankwitt LLP",
]


def normalize_firm_name_for_matching(name):
    """Normalize firm name for fuzzy matching"""
    import re
    # Remove punctuation variations
    normalized = re.sub(r'[,.]', '', name.lower())
    # Normalize whitespace
    normalized = re.sub(r'\s+', ' ', normalized).strip()
    # Handle & variations
    normalized = normalized.replace(' and ', ' & ')
    return normalized


def find_firms_by_reference(text):
    """
    Find law firms in text by checking against reference list.
    Returns set of firm names found.
    """
    import re
    found_firms = set()

    text_lower = text.lower()

    for firm in MAJOR_LAW_FIRMS:
        # Try exact match first (case insensitive)
        if firm.lower() in text_lower:
            found_firms.add(firm)
            continue

        # Try without punctuation
        firm_normalized = normalize_firm_name_for_matching(firm)
        text_normalized = normalize_firm_name_for_matching(text)

        if firm_normalized in text_normalized:
            found_firms.add(firm)

    return found_firms
